DEBUG = 1
INFO = 2
WARNING = 3
ERROR = 4
CRITICAL = 5

BAB = 'bab'
ERAN = 'eran'
MARABOU = 'marabou'
MIPVERIFY = 'mipverify'
NEURIFY = 'neurify'
NNENUM = 'nnenum'
PLANET = 'planet'
RELUPLEX = 'reluplex'
VERINET = 'verinet'

VERIFIERS = [BAB, ERAN, MARABOU, MIPVERIFY, NEURIFY, NNENUM, PLANET, RELUPLEX, VERINET]
RUNABLE_VERIFIERS = [MARABOU, NEURIFY, NNENUM, PLANET]
