from .common.base import BaseEnum

DEBUG = 1
INFO = 2
WARNING = 3
ERROR = 4
CRITICAL = 5

DNNV = 'dnnv'
VERISIG = 'verisig'
MARABOU = 'marabou'


class DNNV_VERIFIER(BaseEnum):
    BAB = 'dnnv_bab'
    ERAN = 'dnnv_eran'
    MARABOU = 'dnnv_marabou'
    MIPVERIFY = 'dnnv_mipverify'
    NEURIFY = 'dnnv_neurify'
    NNENUM = 'dnnv_nnenum'
    PLANET = 'dnnv_planet'
    RELUPLEX = 'dnnv_reluplex'
    VERINET = 'dnnv_verinet'


class VERIFIER(BaseEnum):
    DNNV = 'dnnv'
    VERISIG = 'verisig'
    MARABOU = 'marabou'


DNNV_VERIFIERS = [DNNV_VERIFIER.BAB, DNNV_VERIFIER.ERAN, DNNV_VERIFIER.MARABOU, DNNV_VERIFIER.MIPVERIFY,
                  DNNV_VERIFIER.NEURIFY, DNNV_VERIFIER.NNENUM, DNNV_VERIFIER.PLANET, DNNV_VERIFIER.RELUPLEX, DNNV_VERIFIER.VERINET]
DNNV_RUNABLE_VERIFIERS = [DNNV_VERIFIER.MARABOU, DNNV_VERIFIER.NEURIFY, DNNV_VERIFIER.NNENUM, DNNV_VERIFIER.PLANET]

STYLE_RED = "\033[31m"
STYLE_GREEN = "\033[32m"
STYLE_YELLOW = "\033[33m"
STYLE_BLUE = "\033[34m"
STYLE_MAGENTA = "\033[35m"
STYLE_CYAN = "\033[36m"
STYLE_WHITE = "\033[37m"
STYLE_BOLD = "\033[1m"
STYLE_UNDERLINE = "\033[4m"
STYLE_RESET = "\033[0m"

INTERACTIVE_ITYPE_y_or_N = "y/N"
INTERACTIVE_ITYPE_Y_or_n = "Y/n"
