DEBUG = 1
INFO = 2
WARNING = 3
ERROR = 4
CRITICAL = 5

BAB = 'bab'
ERAN = 'eran'
MARABOU = 'marabou'
MIPVERIFY = 'mipverify'
NEURIFY = 'neurify'
NNENUM = 'nnenum'
PLANET = 'planet'
RELUPLEX = 'reluplex'
VERINET = 'verinet'

VERIFIERS = [BAB, ERAN, MARABOU, MIPVERIFY, NEURIFY, NNENUM, PLANET, RELUPLEX, VERINET]
RUNABLE_VERIFIERS = [MARABOU, NEURIFY, NNENUM, PLANET]

STYLE_RED = "\033[31m"
STYLE_GREEN = "\033[32m"
STYLE_YELLOW = "\033[33m"
STYLE_BLUE = "\033[34m"
STYLE_MAGENTA = "\033[35m"
STYLE_CYAN = "\033[36m"
STYLE_WHITE = "\033[37m"
STYLE_BOLD = "\033[1m"
STYLE_UNDERLINE = "\033[4m"
STYLE_RESET = "\033[0m"

INTERACTIVE_ITYPE_y_or_N = "y/N"
INTERACTIVE_ITYPE_Y_or_n = "Y/n"